// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "address": {
      name: "address",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/address.tsx"],
      component: React.lazy(() => import("@/registry/default/components/address.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "text": {
      name: "text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/text.tsx"],
      component: React.lazy(() => import("@/registry/default/components/text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/avatar.tsx"],
      component: React.lazy(() => import("@/registry/default/components/avatar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "background-image": {
      name: "background-image",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/background-image.tsx"],
      component: React.lazy(() => import("@/registry/default/components/background-image.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/badge.tsx"],
      component: React.lazy(() => import("@/registry/default/components/badge.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "banner": {
      name: "banner",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/banner.tsx"],
      component: React.lazy(() => import("@/registry/default/components/banner.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "column": {
      name: "column",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/column.tsx"],
      component: React.lazy(() => import("@/registry/default/components/column.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "container": {
      name: "container",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/container.tsx"],
      component: React.lazy(() => import("@/registry/default/components/container.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/progress.tsx"],
      component: React.lazy(() => import("@/registry/default/components/progress.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "row": {
      name: "row",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/row.tsx"],
      component: React.lazy(() => import("@/registry/default/components/row.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "transaction-result": {
      name: "transaction-result",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/transaction-result.tsx"],
      component: React.lazy(() => import("@/registry/default/components/transaction-result.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "user-banner": {
      name: "user-banner",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/user-banner.tsx"],
      component: React.lazy(() => import("@/registry/default/components/user-banner.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: ["registry/default/components/card.tsx"],
      component: React.lazy(() => import("@/registry/default/components/card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
